// Active V10 components
export { default as WorkspacesTable } from './WorkspacesTable'
export { default as SeatsPageHeader } from './SeatsPageHeader'
export { default as SeatsStatCards } from './SeatsStatCards'
export { default as SeatsTableToolbar } from './SeatsTableToolbar'
export { default as SeatsTableRow, SeatsTableRowSkeleton } from './SeatsTableRow'
export * from './dialogs'
export { default as WorkspacePermissionOverrideDialog } from './WorkspacePermissionOverrideDialog'
export { default as AddWorkspaceDialog } from './AddWorkspaceDialog'
export { default as QuickWorkspaceEdit } from './QuickWorkspaceEdit'
export { default as ManageRolesPanel } from './ManageRolesPanel'
export { default as ManageGroupsPanel } from './ManageGroupsPanel'

// Legacy/shared components
export { default as UserSidebar } from './UserSidebar'
export { default as UserQuickEditSidebar } from './UserQuickEditSidebar'
export { default as UserPermissionsDialog } from './UserPermissionsDialog'
export { default as UserProfileTab } from './UserProfileTab'
export { default as UserAccessTab } from './UserAccessTab'
export { default as UserWorkspacesTab } from './UserWorkspacesTab'
export { default as AddUserDialog } from './AddUserDialog'
export { default as AddPermissionOverrideDialog } from './AddPermissionOverrideDialog'
export { default as PermissionOverridesPanel } from './PermissionOverridesPanel'
export { default as WorkspacePermissionsPanel } from './WorkspacePermissionsPanel'
export { default as QuickRoleAssign } from './QuickRoleAssign'
export { default as QuickGroupsAssign } from './QuickGroupsAssign'
export { default as QuickBulkSeatChange } from './QuickBulkSeatChange'
export { default as QuickBulkRoleAssign } from './QuickBulkRoleAssign'
export { default as QuickBulkGroupsAssign } from './QuickBulkGroupsAssign'
export { default as BulkActionBar } from './BulkActionBar'
export { default as PermissionToggle } from './PermissionToggle'
